"""Data models for iLink protocol messages and API types."""

from ilink_bot.models.messages import (
    BotInfo,
    CDNMedia,
    FileItem,
    ImageItem,
    Message,
    MessageItem,
    MessageItemType,
    MessageState,
    MessageType,
    QRCode,
    RefMessage,
    SendMessageRequest,
    TextItem,
    UpdatesResponse,
    UploadMediaType,
    VideoItem,
    VoiceItem,
    WeChatMessage,
)

__all__ = [
    "BotInfo",
    "CDNMedia",
    "FileItem",
    "ImageItem",
    "Message",
    "MessageItem",
    "MessageItemType",
    "MessageState",
    "MessageType",
    "QRCode",
    "RefMessage",
    "SendMessageRequest",
    "TextItem",
    "UpdatesResponse",
    "UploadMediaType",
    "VideoItem",
    "VoiceItem",
    "WeChatMessage",
]
